### ISSUE TITLE
classpath and "models" dir

### ISSUE THREAD

**Issue by arnelandwehr** [CedricGatay/play-querydsl#1]
Hi,

thx for providing this plugin! At the moment i work on a Play/Java application where we want to use querydsl together with spring data. Therefor we want to generate the querydsl metamodel classes with your plugin. 

At the moment we have 2 problems:
1. The annotation processor scans our complete project which results in an error. As we have a mixture of scala and java classes, the processor tries to compile a Java class that references a scala class. Unfortunately the scala class is not on the classpath at this moment (i guess it's not even compiled until then). It would be great if the annotation processor would only work on the files in the given "models" directory. 
2. I was not able to set the "queryDSLPackage" to our "app/x/y/z/models" package. Adding the line QueryDSLPlugin.queryDSLPackage := "com.codetroopers.app.models" to my Build.sbt file had no visible impact. At the moment we use a workaround by providing a dummy entity in a dummy models package. That triggers the annotation processor and it generates than also the metamodels for the entities in our "app/x/y/z/models" package.

As my scala (and sbt knowledge...) is still quiet limited i was not able to provide a working Pull Requests that could fix these problems.

Best regards,

   Arne

**Comment by CedricGatay** [comment]
It should be ok now using slash separator and the newest version of the plugin, sorry for the time taken to update and fix it.
