### ISSUE TITLE
Classpath issues when compiling

### ISSUE THREAD

**Issue by thelateperseus** [CedricGatay/play-querydsl#2]
Thanks a bunch for writing this plugin - I wouldn't have used QueryDSL without it.

I think this is a similar problem to [Issue 1 (point 1)](https://github.com/CedricGatay/play-querydsl/issues/1):

I have several sub-packages for templates: `visualisations` and `admin`.  When compiling the QueryDSL metamodel, I get the following build output:

```
[warn] Note: Running JPAAnnotationProcessor
[warn] Note: Serializing Entity types
[warn] Note: Generating models.QCommittee for [models.Committee]
[warn] Note: Generating models.QAppUser for [models.AppUser]
[warn] Note: Running JPAAnnotationProcessor
[warn] C:\Users\Nathan\Documents\Dev\avid-study\app\controllers\Committees.java:23: error: package views.html.admin does not exist
[warn] import views.html.admin.*;
[warn] ^
[warn] C:\Users\Nathan\Documents\Dev\avid-study\app\controllers\Visualisations.java:20: error: package views.html.visualisations does not exist
[warn] import views.html.visualisations.*;
[warn] ^
[warn] Note: Running JPAAnnotationProcessor
[info] Compiling 38 Scala sources and 18 Java sources to C:\Users\Nathan\Documents\Dev\avid-study\target\scala-2.10\classes...
[success] Total time: 23 s, completed 09/06/2014 12:26:14 AM
```

This does not cause me a problem when running on my local machine, but it does *sometimes* cause a problem when I deploy to Heroku.  I get the same "warn" messages, followed by an exception.  The exception text definitely seems related to the above warnings and I was going to post it here, but I can't get it to occur right now.  I just re-pushed to Heroku and it worked fine - if I get the exception again, I'll add it to this issue.

I managed to work around the warning by adding the following empty class to each affected package:

```
package views.html.admin;

public class Empty {
}
```

I think the problem is that the annotations processor is compiling the controllers which reference the templates which haven't been compiled yet.  The models shouldn't reference the controllers, so the controllers shouldn't be necessary to produce the metamodel.

Any help or suggestions would be greatly appreciated.

**Comment by CedricGatay** [comment]
If the problem still exists for you, you might want to give 0.1.2 a try, as it fixes package scanning.

**Comment by CedricGatay** [comment]
No carrier. Closing
