### ISSUE TITLE
Enum not correctly generated in Q file

### ISSUE THREAD

**Issue by Clandestino** [CedricGatay/play-querydsl#6]
Hello,
I just created a new project with activator and playJava.
My build.sbt :

``` sbt
import play.sbt.PlayImport._
name := """querdsl"""
version := "1.0-SNAPSHOT"
lazy val root = (project in file(".")).enablePlugins(PlayJava,QueryDSLPlugin)
queryDSLPackage := "models"
scalaVersion := "2.11.6"
libraryDependencies ++= Seq(
  javaJdbc,
  cache,
  javaWs,
  javaJpa,
  "org.hibernate" % "hibernate-entitymanager" % "4.3.10.Final"
)
routesGenerator := InjectedRoutesGenerator
```

My plugins.sbt :

``` sbt
// The Play plugin
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.4.2")
// Web plugins
addSbtPlugin("com.typesafe.sbt" % "sbt-coffeescript" % "1.0.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-less" % "1.0.6")
addSbtPlugin("com.typesafe.sbt" % "sbt-jshint" % "1.0.3")
addSbtPlugin("com.typesafe.sbt" % "sbt-rjs" % "1.0.7")
addSbtPlugin("com.typesafe.sbt" % "sbt-digest" % "1.1.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-mocha" % "1.1.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-play-enhancer" % "1.1.0")
addSbtPlugin("com.code-troopers.play" % "play-querydsl" % "0.1.2")
```

I created just one model : 

``` java
package models;

import enums.Status;

import javax.persistence.*;

@Entity
@Table(name="User")
public class User {
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID")
    @Id
    private Integer id;

    @Column(name = "Lastname", nullable = false)
    private String lastname;

    @Column(name = "Firstname", nullable = false)
    private String firstname;

    @Column(name = "Status", nullable = false)
    @Enumerated(EnumType.STRING)
    private Status status;
}
```

And the enum :

``` java
package enums;
public enum Status {
    UP,
    DOWN
}
```

And the generated QUser :

``` java
package models;
import static com.mysema.query.types.PathMetadataFactory.*;
import com.mysema.query.types.path.*;
import com.mysema.query.types.PathMetadata;
import javax.annotation.Generated;
import com.mysema.query.types.Path;
/**
 * QUser is a Querydsl query type for User
 */
@Generated("com.mysema.query.codegen.EntitySerializer")
public class QUser extends EntityPathBase<User> {
    private static final long serialVersionUID = 1339629807L;
    public static final QUser user = new QUser("user");
    public final StringPath firstname = createString("firstname");
    public final NumberPath<Integer> id = createNumber("id", Integer.class);
    public final StringPath lastname = createString("lastname");
    public final NumberPath<Status> status = createNumber("status", Status.class);
    public QUser(String variable) {
        super(User.class, forVariable(variable));
    }
    public QUser(Path<? extends User> path) {
        super(path.getType(), path.getMetadata());
    }
    public QUser(PathMetadata<?> metadata) {
        super(User.class, metadata);
    }
}
```

We can see that the field status is wrong generated it should be :
public final EnumPath<enums.Status> status = createEnum("status", enums.Status.class);

any idea why the enum is converted numberPath instead enumPath?

Thanks for your answer.

**Comment by CedricGatay** [comment]
Hello,
thank for your feedback. As generation is handled by QueryDSL, it might be a QueryDSL issue, could you try with a more recent version to see if it persists ?

Regards,

**Comment by Clandestino** [comment]
Hello Cedric,
Thank you for your answer.
How can I change the version ? I tried to put queryDSLVersion := "4.0.3" on build.sbt but doesn't work. I am not familiar with scala and new on play.
Regards

**Comment by CedricGatay** [comment]
I don't have much time to look at your issue these days. But as far as I remember setting the version this way should work.
You might try to inspect the sbt build to see what it is taking into account.

**Comment by Clandestino** [comment]
I find the problem. My package who contains my enums is not under models (who is scanned by querydsl), when I move my enums under models (models.enums.<My enums>) it's work. It is possible to tell querydsl to scann two packages?
Thank you for your help.

**Comment by CedricGatay** [comment]
Hum, I am afraid not in the current version. It will need an improvement of the plugin unfortunately at roughly https://github.com/CedricGatay/play-querydsl/blob/master/library/src/main/scala/QueryDSLPlugin.scala#L46 to handle a list of packages to scan and do a merge of the returned files. 
I am providing the reference just in case you've got spare time to contribute ;)

Glad you find out why anyway.

**Comment by Clandestino** [comment]
I will be happy to help in a few weeks when my skills in scala will be better.
For now the better solutions to me is to put querydslPackage on the root : 
queryDSLPackage := ""

**Comment by CedricGatay** [comment]
As long as it works fine for you, I'm convinced. May I close this thread ?

**Comment by Clandestino** [comment]
Yes sure, you can close. Thank you a lot for the answers and the greet job on the plugin ;-)
